# Generated by Django 3.1.6 on 2023-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Numéro_de_téléphone', models.CharField(max_length=10)),
                ('Type', models.CharField(choices=[('WiFi', 'Problème avec mon réseau Wifi'), ('Virus', 'Suspicion de virus sur mon réseau'), ('Nettoyage', 'Nettoyage de mon ordinateur'), ('Développement web', 'Initiation au développement web'), ('Cours', 'Cours informatique tout niveau'), ('Dépannage', 'Dépannage informatique, problème matériel'), ('Récupération données', 'Récupération de données'), ('Autre', '(Autre)')], max_length=50)),
                ('Localité', models.CharField(choices=[('Longjumeau', 'Longjumeau'), ('Ballainvilliers', 'Ballainvilliers'), ('Brétigny sur Orge', 'Brétigny-sur-Orge'), ('Longpont sur Orge', 'Longpont-sur-Orge'), ('Villiers sur Orge', 'Villiers-sur-Orge'), ('Savigny sur Orge', 'Savigny-sur-Orge'), ('Epinay sur Orge', 'Épinay-sur-Orge'), ('Ville du Bois', 'Ville-du-Bois'), ('Nozay', 'Nozay'), ('Linas', 'Linas'), ('Montlhéry', 'Montlhéry'), ('Autre', '(Autre)')], max_length=50, null=True)),
                ('Description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Formulaire',
            },
        ),
    ]
