# Generated by Django 3.1.6 on 2023-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Type', models.CharField(choices=[('Choix', '(Choisissez parmi ces propositions)'), ('WiFi', 'Problème avec mon réseau (WiFi / Ethernet / autre)'), ('Virus', 'Suspicion de virus sur mon réseau'), ('Leçon', "Besoin d'un cours d'informatique"), ('Cours logiciel', "Besoin d'un cours sur un logiciel"), ('Dépannage', 'Dépannage informatique matériel'), ('Récupération données', 'Récupération de données sur ordinateur ne fonctionnant plus'), ('Autre', 'Autre')], max_length=50)),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
