# Generated by Django 3.1.6 on 2023-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulairemodel',
            old_name='Localite',
            new_name='Localité',
        ),
        migrations.AddField(
            model_name='formulairemodel',
            name='Numéro_de_telephone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
