# Generated by Django 3.1.6 on 2023-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairemodel',
            name='Localite',
            field=models.CharField(choices=[('Longjumeau', 'Longjumeau'), ('Ballainvilliers', 'Ballainvilliers'), ('Brétigny sur Orge', 'Brétigny-sur-Orge'), ('Longpont sur Orge', 'Longpont-sur-Orge'), ('Villiers sur Orge', 'Villiers-sur-Orge'), ('Savigny sur Orge', 'Savigny-sur-Orge'), ('Epinay sur Orge', 'Épinay-sur-Orge'), ('Ville du Bois', 'Ville-du-Bois'), ('Nozay', 'Nozay'), ('Linas', 'Linas'), ('Montlhéry', 'Montlhéry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formulairemodel',
            name='Type',
            field=models.CharField(choices=[('WiFi', 'Problème avec mon réseau (WiFi / Ethernet / autre)'), ('Virus', 'Suspicion de virus sur mon réseau'), ('Nettoyage', 'Nettoyage de mon ordinateur'), ('Leçon', "Besoin d'un cours d'informatique"), ('Cours logiciel', "Besoin d'un cours sur un logiciel"), ('Dépannage', 'Dépannage informatique matériel'), ('Récupération données', 'Récupération de données sur ordinateur ne fonctionnant plus'), ('Autre', '(Autre)')], max_length=50),
        ),
    ]
