# Generated by Django 3.1.6 on 2023-04-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_auto_20230402_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulairemodel',
            options={'verbose_name': 'Formulaire'},
        ),
    ]
